[tools]
aws-vault = "latest"
awscli = "latest"
bat = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
github-cli = "latest"
go = "latest"
jq = "latest"
kubectl = "latest"
kubectx = "latest"
neovim = "latest"
node = "20.16.0"
pnpm = "9.7"
starship = "latest"
terraform = "1.9"
terragrunt = "0.67"
tflint = "0.53.0"
tree-sitter = "latest"
