[tools]
bat = "latest"
neovim = "latest"
awscli = "latest"
kubectl = "latest"
starship = "latest"
fd = "latest"
tree-sitter = "latest"
kubectx = "latest"
node = "latest"
delta = "latest"
fzf = "latest"
go = "latest"
